import { z } from "zod";
const nullableUrl=(m:string)=>z.string().url(m).optional().nullable().or(z.literal(""));
const invitationBaseSchema={
 templateId:z.string().min(1,"Template wajib dipilih"), slug:z.string().min(3,"Slug minimal 3 karakter").max(60).regex(/^[a-z0-9]+(-[a-z0-9]+)*$/,"Slug hanya boleh huruf kecil, angka, dan tanda strip"), title:z.string().min(3,"Judul minimal 3 karakter").max(150), groomName:z.string().max(100).optional().nullable(), brideName:z.string().max(100).optional().nullable(), groomParents:z.string().max(150).optional().nullable(), brideParents:z.string().max(150).optional().nullable(), groomInstagram:z.string().max(50).regex(/^[a-zA-Z0-9._]*$/,"Tanpa @ atau spasi, cuma huruf/angka/titik/underscore").optional().nullable().or(z.literal("")), brideInstagram:z.string().max(50).regex(/^[a-zA-Z0-9._]*$/,"Tanpa @ atau spasi, cuma huruf/angka/titik/underscore").optional().nullable().or(z.literal("")), eventDate:z.preprocess(v=>(v===""||v===null?undefined:v),z.coerce.date().optional().nullable()), eventLocation:z.string().max(150).optional().nullable(), eventAddress:z.string().max(255).optional().nullable(), eventMapsUrl:nullableUrl("URL Maps tidak valid"), description:z.string().max(2000).optional().nullable(), coverImageUrl:nullableUrl("URL cover tidak valid"), coverImagePublicId:z.string().max(255).optional().nullable().or(z.literal("")), coverImagePositionX:z.number().int().min(0).max(100).default(50), coverImagePositionY:z.number().int().min(0).max(100).default(50), groomPhotoUrl:nullableUrl("URL foto mempelai pria tidak valid"), groomPhotoPublicId:z.string().max(255).optional().nullable().or(z.literal("")), groomPhotoPositionX:z.number().int().min(0).max(100).default(50), groomPhotoPositionY:z.number().int().min(0).max(100).default(50), bridePhotoUrl:nullableUrl("URL foto mempelai wanita tidak valid"), bridePhotoPublicId:z.string().max(255).optional().nullable().or(z.literal("")), bridePhotoPositionX:z.number().int().min(0).max(100).default(50), bridePhotoPositionY:z.number().int().min(0).max(100).default(50), quote:z.string().max(500).optional().nullable(), videoUrl:nullableUrl("URL video tidak valid")
};
export const eventItemSchema=z.object({ type:z.string().max(40).optional().nullable().or(z.literal("")), title:z.string().min(1,"Nama event wajib diisi").max(80), eventDate:z.preprocess(v=>(v===""||v===null?undefined:v),z.coerce.date().optional().nullable()), startTime:z.string().max(10).optional().nullable().or(z.literal("")), endTime:z.string().max(10).optional().nullable().or(z.literal("")), location:z.string().max(150).optional().nullable(), address:z.string().max(255).optional().nullable(), mapsUrl:nullableUrl("URL Maps tidak valid") });
export const eventItemFormSchema=z.object({ type:z.string().max(40).optional().nullable().or(z.literal("")), title:z.string().min(1,"Nama event wajib diisi").max(80), eventDate:z.string().optional().nullable(), startTime:z.string().max(10).optional().nullable().or(z.literal("")), endTime:z.string().max(10).optional().nullable().or(z.literal("")), location:z.string().max(150).optional().nullable(), address:z.string().max(255).optional().nullable(), mapsUrl:nullableUrl("URL Maps tidak valid") });
export const galleryItemSchema=z.object({imageUrl:z.string().url("URL foto tidak valid"),imagePublicId:z.string().max(255).optional().nullable().or(z.literal("")),caption:z.string().max(150).optional().nullable()});
export const storyItemSchema=z.object({title:z.string().min(1,"Judul momen wajib diisi").max(100),date:z.string().max(50).optional().nullable(),description:z.string().min(1,"Cerita wajib diisi").max(500)});
export const giftItemSchema=z.discriminatedUnion("method",[z.object({method:z.literal("BANK_TRANSFER"),bankName:z.string().min(1,"Nama bank wajib diisi"),accountNumber:z.string().min(1,"Nomor rekening wajib diisi"),accountHolder:z.string().min(1,"Nama pemilik rekening wajib diisi"),note:z.string().max(150).optional().nullable()}),z.object({method:z.literal("E_WALLET"),ewalletName:z.string().min(1,"Nama e-wallet wajib diisi"),ewalletNumber:z.string().min(1,"Nomor e-wallet wajib diisi"),note:z.string().max(150).optional().nullable()})]);
export const createInvitationSchema=z.object(invitationBaseSchema); export const updateInvitationSchema=z.object(invitationBaseSchema).partial();
export const invitationWizardSchema=z.object({...invitationBaseSchema,events:z.array(eventItemSchema).max(10).default([]),gallery:z.array(galleryItemSchema).max(20).default([]),gifts:z.array(giftItemSchema).max(10).default([]),stories:z.array(storyItemSchema).max(20).default([])});
export const invitationWizardFormSchema=z.object({templateId:invitationBaseSchema.templateId,slug:invitationBaseSchema.slug,title:invitationBaseSchema.title,groomName:invitationBaseSchema.groomName,brideName:invitationBaseSchema.brideName,groomParents:invitationBaseSchema.groomParents,brideParents:invitationBaseSchema.brideParents,groomInstagram:invitationBaseSchema.groomInstagram,brideInstagram:invitationBaseSchema.brideInstagram,eventDate:z.string().optional().nullable(),eventLocation:invitationBaseSchema.eventLocation,eventAddress:invitationBaseSchema.eventAddress,eventMapsUrl:invitationBaseSchema.eventMapsUrl,description:invitationBaseSchema.description,coverImageUrl:invitationBaseSchema.coverImageUrl,coverImagePublicId:invitationBaseSchema.coverImagePublicId,coverImagePositionX:invitationBaseSchema.coverImagePositionX,coverImagePositionY:invitationBaseSchema.coverImagePositionY,groomPhotoUrl:invitationBaseSchema.groomPhotoUrl,groomPhotoPublicId:invitationBaseSchema.groomPhotoPublicId,groomPhotoPositionX:invitationBaseSchema.groomPhotoPositionX,groomPhotoPositionY:invitationBaseSchema.groomPhotoPositionY,bridePhotoUrl:invitationBaseSchema.bridePhotoUrl,bridePhotoPublicId:invitationBaseSchema.bridePhotoPublicId,bridePhotoPositionX:invitationBaseSchema.bridePhotoPositionX,bridePhotoPositionY:invitationBaseSchema.bridePhotoPositionY,quote:invitationBaseSchema.quote,videoUrl:invitationBaseSchema.videoUrl,events:z.array(eventItemFormSchema).max(10).default([]),gallery:z.array(galleryItemSchema).max(20).default([]),gifts:z.array(giftItemSchema).max(10).default([]),stories:z.array(storyItemSchema).max(20).default([])});
export type CreateInvitationSchema=z.infer<typeof createInvitationSchema>; export type UpdateInvitationSchema=z.infer<typeof updateInvitationSchema>; export type InvitationWizardSchema=z.infer<typeof invitationWizardSchema>; export type InvitationWizardFormValues=z.infer<typeof invitationWizardFormSchema>; export type EventItemSchema=z.infer<typeof eventItemSchema>; export type GalleryItemSchema=z.infer<typeof galleryItemSchema>; export type StoryItemSchema=z.infer<typeof storyItemSchema>; export type GiftItemSchema=z.infer<typeof giftItemSchema>;
